# Generated by Django 4.1.5 on 2023-02-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_attraction_alter_feeding_options_alter_feeding_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shore',
            name='attractions',
            field=models.ManyToManyField(to='main_app.attraction'),
        ),
    ]
