# Generated by Django 4.1.5 on 2023-02-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_shore_attractions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='shore',
        ),
        migrations.AddField(
            model_name='feeding',
            name='attraction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.attraction'),
            preserve_default=False,
        ),
    ]
