# Generated by Django 4.1.5 on 2023-02-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_shore_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeding',
            new_name='Reservation',
        ),
    ]
